version: "3"

services:
    bot:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: "weather-telegram-bot"
        restart: always
        env_file:
          - bot_app/.env
